[pytest]
# pytest 자동화

# 콘솔에 logger 출력
log_cli = true

# INFO 레벨 이상 출력
log_cli_level = INFO

# 로그 출력 형식
log_cli_format = %(asctime)s [%(levelname)s] %(filename)s:%(lineno)d - %(message)s

# 시간 형식
log_cli_date_format = %Y-%m-%d %H:%M:%S

# pytest 기본 옵션
addopts = -v -s --tb=short